---
env:
  global:
    - CC_TEST_REPORTER_ID=c44688920dead3a9dede2a870a3b55be7293061a1f76001496f2abce60f1598d
sudo: false
language: ruby
cache: bundler
rvm:
  - 1.9.3
before_install: gem install bundler -v 1.16.6

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
